### ISSUE TITLE
Not able to delete attachments gives server error.

### ISSUE THREAD

**Issue by usmanaftab** [svkanoria/rails-app-starter-kit#16]
NoMethodError (undefined method `user_id' for #<Class:0x007fca9c1e9268>):
  app/policies/attachment_policy.rb:20:in `update?'
  app/policies/attachment_policy.rb:24:in `destroy?'
  app/controllers/concerns/batch_actions.rb:63:in `authorize_batch_action'

**Comment by svkanoria** [comment]
Not able to replicate Attachments are deleting correctly. Closing for now.
